version: 2.1

jobs:
  build:
    parameters:
      python_version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python_version >>-node
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install JavaScript dependencies
          command: cd labdiscoveryengine/static && npm install
      - run:
          name: Build assets
          command: . devrc && flask assets build
      - run:
          name: Run tests
          command: pytest tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          name: unit-tests-cpython<< matrix.python_version >>
          matrix:
            parameters:
              python_version: ["3.10", "3.11"]
