version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install JavaScript dependencies
          command: cd labdiscoveryengine/static && npm install
      - run:
          name: Build assets
          command: . devrc && flask assets build
      - run:
          name: Run tests
          command: pytest tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
